[package]
name = "persistence"
version = "0.1.0"
authors = ["Benjamin Eder <barny.eder@gmail.com>"]
edition = "2018"

[dependencies]
home = "0.5.3"
chrono = "0.4.19"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]
